# ddos_malisius
ERRAMIENTA ECHA EN PYTHON Y EN SSH

